# Generated by Django 5.1.7 on 2025-04-01 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BusPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'role': 'park_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_parks', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('origin_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buspark')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='IndirectRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField()),
                ('total_price', models.FloatField()),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirect_ends', to='core.city')),
                ('start_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirect_starts', to='core.buspark')),
                ('transit_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_points', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_routes', to='core.city')),
                ('origin_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.buspark')),
            ],
        ),
    ]
