# Generated by Django 5.1.7 on 2025-04-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bus_seat_trip_seatreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='core.buspark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('on_trip', 'Currently on Trip')], default='available', max_length=20),
        ),
    ]
