# Generated by Django 5.1.7 on 2025-04-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trip_available_seats_alter_booking_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
