# Generated by Django 5.1.7 on 2025-04-05 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buspark',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'park_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_parks', to=settings.AUTH_USER_MODEL),
        ),
    ]
