# Generated by Django 5.1.7 on 2025-04-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bus_driver_name_bus_park_bus_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['state', 'name']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='origin_park',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.trip'),
        ),
        migrations.AddField(
            model_name='buspark',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='buspark',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='seat_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
